### ISSUE TITLE
Latest SimpleInjector Integration

### ISSUE THREAD

**Issue by emrecengel** [danludwig/tripod#7]
I admire the architectural design in this project, it helped me to understand the design patterns and how efficiently they can be used in a real world application. By the latest SimpleInjector, there are things got obsolete, and there are things that are in use not being recommended by them. I am eager to see what type of replacements you would use with the latest SimpleInjector update.

Thanks in advance

**Comment by janhartmann** [comment]
Not sure if Dan is still maintaining this project, but since I was heavily inspired by his work as well, I have created my "own version" of Tripod. It's updated to newest version of Simple Injector.

You are welcome to peek though it on https://github.com/hartmanns/ScaffoldR for inspiration.

**Comment by danludwig** [comment]
@emrecengel yes I am aware of Tripod's upgrade conflicts with newer versions of Simple Injector due to breaking changes in their API. There is no plan to fix. If you have a specific question after reading the Simple Injector docs, or after looking at @janhartmann's project, I recommend asking on StackOverflow. Steven is pretty active there.

**Comment by emrecengel** [comment]
I will definitely check it out thank you so much @janhartmann and @danludwig
